---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hd-idle
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hd-idle
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hd-idle
    spec:
      nodeSelector:
        kubernetes.io/hostname: talos0
      tolerations:
        - operator: Exists
      containers:
        - name: hd-idle
          image: docker.io/library/debian:trixie-slim@sha256:cedb1ef40439206b673ee8b33a46a03a0c9fa90bf3732f54704f99cb061d2c5a
          command: ["/bin/sh", "-ec"]
          args:
            - |
              apt-get update
              apt-get install -y --no-install-recommends hd-idle
              exec /usr/sbin/hd-idle -d -i 1800
          securityContext:
            privileged: true
          volumeMounts:
            - name: dev
              mountPath: /dev
      volumes:
        - name: dev
          hostPath:
            path: /dev
            type: Directory
