---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hd-idle
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hd-idle
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hd-idle
    spec:
      nodeSelector:
        kubernetes.io/hostname: talos0
      tolerations:
        - operator: Exists
      containers:
        - name: hd-idle
          image: docker.io/library/debian:bookworm-slim@sha256:f9c6a2fd2ddbc23e336b6257a5245e31f996953ef06cd13a59fa0a1df2d5c252
          command: ["/bin/sh", "-ec"]
          args:
            - |
              apt-get update
              apt-get install -y --no-install-recommends hd-idle
              exec /usr/sbin/hd-idle -d -i 1800
          securityContext:
            privileged: true
          volumeMounts:
            - name: dev
              mountPath: /dev
      volumes:
        - name: dev
          hostPath:
            path: /dev
            type: Directory
