---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: openebs
  values:
    localpv-provisioner:
      analytics:
        enabled: false
      localpv:
        basePath: &hostPath /var/mnt/local-storage
      hostpathClass:
        enabled: true
        name: openebs-hostpath
        isDefaultClass: false
        basePath: *hostPath
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
        rawfile:
          enabled: false
      replicated:
        mayastor:
          enabled: false
    loki:
      enabled: false
    alloy:
      enabled: false
    preUpgradeHook:
      enabled: false
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: true
