---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: volsync
spec:
  namespaceSelector:
    matchNames:
      - storage-system
  selector:
    matchLabels:
      app.kubernetes.io/name: volsync
  endpoints:
    - port: https
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
