---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  releaseName: victoria-metrics
  targetNamespace: observability
  chartRef:
    kind: OCIRepository
    name: victoria-metrics-k8s-stack
  dependsOn:
    - name: prometheus-operator-crds
  interval: 1h
  values:
    fullnameOverride: victoria-metrics
    victoria-metrics-operator:
      admissionWebhooks:
        policy: Ignore
        certManager:
          enabled: true
    defaultDashboards:
      enabled: true
      grafanaOperator:
        enabled: true
        spec:
          allowCrossNamespaceImport: true
          instanceSelector:
            matchLabels:
              dashboards: grafana
    external:
      grafana:
        datasource: VictoriaMetrics
        host: https://grafana.${APP_DOMAIN}
    grafana:
      enabled: false
    kubeEtcd:
      vmScrape:
        spec:
          endpoints:
            - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              port: http-metrics
              scheme: http
      service:
        port: 2381
        selector:
          component: kube-apiserver
        targetPort: 2381
    kubeApiServer:
      vmScrape:
        spec:
          endpoints:
            - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              port: https
              scheme: https
              max_scrape_size: "33554432"
              tlsConfig:
                caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                serverName: kubernetes
    kubeControllerManager:
      vmScrape:
        spec:
          endpoints:
            - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              port: http-metrics
              scheme: https
              tlsConfig:
                caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecureSkipVerify: true
    kubeScheduler:
      vmScrape:
        spec:
          endpoints:
            - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              port: http-metrics
              scheme: https
              tlsConfig:
                caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecureSkipVerify: true
    kubeProxy:
      enabled: false
    kubelet:
      vmScrape:
        spec:
          metricRelabelConfigs:
            - action: labeldrop
              regex: (uid)
            - action: labeldrop
              regex: (id|name)
            - action: drop
              regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
              source_labels:
                - __name__
            - action: labeldrop
              regex: (beta_kubernetes_io_.+|kubernetes_io_.+|kubevirt_io_.+|cpu_feature_node_kubevirt_io_.+|host_model_required_features_node_kubevirt_io_.+|machine_type_node_kubevirt_io_.+|hyperv_node_kubevirt_io_.+|scheduling_node_kubevirt_io_.+)
          relabelConfigs:
            - sourceLabels:
                - __meta_kubernetes_node_name
              targetLabel: node
            - sourceLabels:
                - __metrics_path__
              targetLabel: metrics_path
            - targetLabel: job
              replacement: kubelet
    kube-state-metrics:
      rbac:
        extraRules:
          - apiGroups:
              - source.toolkit.fluxcd.io
              - kustomize.toolkit.fluxcd.io
              - helm.toolkit.fluxcd.io
            resources:
              - gitrepositories
              - buckets
              - helmrepositories
              - ocirepositories
              - kustomizations
              - helmreleases
            verbs:
              - list
              - watch
      customResourceState:
        enabled: true
        config:
          spec:
            resources:
              - groupVersionKind:
                  group: kustomize.toolkit.fluxcd.io
                  version: v1
                  kind: Kustomization
                metricNamePrefix: gotk
                metrics:
                  - name: resource_info
                    help: The current state of a Flux Kustomization resource.
                    each:
                      type: Info
                      info:
                        labelsFromPath:
                          name:
                            - metadata
                            - name
                    labelsFromPath:
                      exported_namespace:
                        - metadata
                        - namespace
                      ready:
                        - status
                        - conditions
                        - "[type=Ready]"
                        - status
                      suspended:
                        - spec
                        - suspend
                      revision:
                        - status
                        - lastAppliedRevision
                      source_name:
                        - spec
                        - sourceRef
                        - name
              - groupVersionKind:
                  group: helm.toolkit.fluxcd.io
                  version: v2
                  kind: HelmRelease
                metricNamePrefix: gotk
                metrics:
                  - name: resource_info
                    help: The current state of a Flux HelmRelease resource.
                    each:
                      type: Info
                      info:
                        labelsFromPath:
                          name:
                            - metadata
                            - name
                    labelsFromPath:
                      exported_namespace:
                        - metadata
                        - namespace
                      ready:
                        - status
                        - conditions
                        - "[type=Ready]"
                        - status
                      suspended:
                        - spec
                        - suspend
                      revision:
                        - status
                        - history
                        - "0"
                        - chartVersion
                      chart_name:
                        - status
                        - history
                        - "0"
                        - chartName
                      chart_app_version:
                        - status
                        - history
                        - "0"
                        - appVersion
                      chart_ref_name:
                        - spec
                        - chartRef
                        - name
                      chart_source_name:
                        - spec
                        - chart
                        - spec
                        - sourceRef
                        - name
              - groupVersionKind:
                  group: source.toolkit.fluxcd.io
                  version: v1
                  kind: GitRepository
                metricNamePrefix: gotk
                metrics:
                  - name: resource_info
                    help: The current state of a Flux GitRepository resource.
                    each:
                      type: Info
                      info:
                        labelsFromPath:
                          name:
                            - metadata
                            - name
                    labelsFromPath:
                      exported_namespace:
                        - metadata
                        - namespace
                      ready:
                        - status
                        - conditions
                        - "[type=Ready]"
                        - status
                      suspended:
                        - spec
                        - suspend
                      revision:
                        - status
                        - artifact
                        - revision
                      url:
                        - spec
                        - url
              - groupVersionKind:
                  group: source.toolkit.fluxcd.io
                  version: v1
                  kind: Bucket
                metricNamePrefix: gotk
                metrics:
                  - name: resource_info
                    help: The current state of a Flux Bucket resource.
                    each:
                      type: Info
                      info:
                        labelsFromPath:
                          name:
                            - metadata
                            - name
                    labelsFromPath:
                      exported_namespace:
                        - metadata
                        - namespace
                      ready:
                        - status
                        - conditions
                        - "[type=Ready]"
                        - status
                      suspended:
                        - spec
                        - suspend
                      revision:
                        - status
                        - artifact
                        - revision
                      endpoint:
                        - spec
                        - endpoint
                      bucket_name:
                        - spec
                        - bucketName
              - groupVersionKind:
                  group: source.toolkit.fluxcd.io
                  version: v1
                  kind: HelmRepository
                metricNamePrefix: gotk
                metrics:
                  - name: resource_info
                    help: The current state of a Flux HelmRepository resource.
                    each:
                      type: Info
                      info:
                        labelsFromPath:
                          name:
                            - metadata
                            - name
                    labelsFromPath:
                      exported_namespace:
                        - metadata
                        - namespace
                      ready:
                        - status
                        - conditions
                        - "[type=Ready]"
                        - status
                      suspended:
                        - spec
                        - suspend
                      revision:
                        - status
                        - artifact
                        - revision
                      url:
                        - spec
                        - url
              - groupVersionKind:
                  group: source.toolkit.fluxcd.io
                  version: v1
                  kind: OCIRepository
                metricNamePrefix: gotk
                metrics:
                  - name: resource_info
                    help: The current state of a Flux OCIRepository resource.
                    each:
                      type: Info
                      info:
                        labelsFromPath:
                          name:
                            - metadata
                            - name
                    labelsFromPath:
                      exported_namespace:
                        - metadata
                        - namespace
                      ready:
                        - status
                        - conditions
                        - "[type=Ready]"
                        - status
                      suspended:
                        - spec
                        - suspend
                      revision:
                        - status
                        - artifact
                        - revision
                      url:
                        - spec
                        - url
    vmsingle:
      route:
        enabled: true
        extraRules:
          - matches:
              - path:
                  type: Exact
                  value: /
            filters:
              - type: RequestRedirect
                requestRedirect:
                  path:
                    type: ReplaceFullPath
                    replaceFullPath: /vmui/
                  statusCode: 302
        hostnames:
          - metrics.${APP_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network-system
      spec:
        replicaCount: 1
        retentionPeriod: 14d
        storage:
          accessModes:
            - ReadWriteOnce
          dataSourceRef:
            apiGroup: volsync.backube
            kind: ReplicationDestination
            name: victoria-metrics-dst
          resources:
            requests:
              storage: 5Gi
          storageClassName: ${APP_STORAGECLASS}
    vmagent:
      spec:
        resources:
          limits:
            cpu: 500m
    alertmanager:
      route:
        enabled: true
        hostnames:
          - alertmanager.${APP_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network-system
      spec:
        externalURL: https://alertmanager.${APP_DOMAIN}
    vmalert:
      route:
        enabled: true
        hostnames:
          - vmalert.${APP_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network-system
      spec:
        extraArgs:
          external.url: https://vmalert.${APP_DOMAIN}
