---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./linstor-cluster-ocirepository.yaml
  - ./linstor-cluster-helmrelease.yaml
  - ./storageclass-linstor-zfs-ssd.yaml
  - ./volumesnapshotclass-linstor-zfs.yaml
  - ./grafanadashboard.yaml
