---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-zfs-ssd
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  linstor.csi.linbit.com/storagePool: ssd
  linstor.csi.linbit.com/placementCount: "3"
  linstor.csi.linbit.com/resourceGroup: linstor-zfs-ssd
