---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network-system

components:
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./cert-manager/ks.yaml
  - ./certificates/ks.yaml
  - ./external-dns-cloudflare/ks.yaml
  - ./external-dns-mikrotik/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./envoy-gateway-resources/ks.yaml
  - ./echo/ks.yaml
