---
apiVersion: v1
kind: Service
metadata:
  name: nas
  annotations:
    lbipam.cilium.io/ips: "${${NETWORK_LB_CIDR%%/*}%.*}.20"
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/domain: nas
  ports:
    - name: nfs4
      port: 2049
      protocol: TCP
      targetPort: 2049
