apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsSecret
metadata:
  name: cloudflare-dns-api-token
  namespace: cert-manager
spec:
  secrets:
    - name: cloudflare-dns-api-token
      stringData:
        token: ENC[AES256_GCM,data:wfyPQUAUyD/PifrY2uEQa3LLNPXu5UYbTarJjZuWKAN2ImKLC5FdMhXqSrEKJmZnW4ADDbQ=,iv:QK6b3fMkMdNivs0AWztZEvIgjXlH1st3YEWAmsevl1U=,tag:bqNALOA3kNxNaOkPwPWuMg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFE1WkIwUSB0Y3FQ
        ZUgxNEVXQWFWQlYzRGhscC9sS2VObkhvNTg0ZkVqaS8rWTFVUnhFCktoT3BxY0Vy
        dER4VUI4ZlpCYTBxeU5VdjlUbVd1VUlCbVgvaGl2N2xoaEkKLS0tIE1Yc3BZWnBw
        R29PMENMc3ArUXVOTGw2SjNWdHREZ2lSTW1QOHhMMWs4elkKwKumkcRbcLrcrPZk
        RURKXetfbgiqcX7hqP5p5BSW5HGjrrdcsRoZ/WVfH75jgLX/roj1fU+cY2xyjXCx
        VUe1lw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAcnmLrPeTJeKsasfU0qn4sP4lBNeOUgRG4iZDS8nyEo kid@vulkan
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE1Wa1kxQSB6SEFv
        Z3lRVjVvL2RQQk9ndThHemhMLzRsNTB5LzVCaXVkUFNLcGU1MjFFCjE1RElwRkxt
        WVd3WjJUUnZybTZaTG81TSsySXNOUXNRVnNlR2VzcmpDOW8KLS0tIG5yRFA4NHND
        dUxzWDlOQktnaE9tRGxod09VcEZmQW1YR3lhRkkxTUwrSDAK5qAIKkyEgk5fihYX
        NA9X/lom7LxNBf5oR5DrmSFriqdhPuoUh/koemeFZkZkmf9mF7OfG3/E2S4ifZUT
        0qHg3g==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHIM3nsk3HxvEcplSqwynh9V2NzlYdI10mrR746SiJZb kid@fw13
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eHZUY3BFUzBacXBLbW5W
        QWp3L2lhQnQ1WGt4ZUhsbjNqMWswdC9Ebkg0CkRZSU9zcFdvZTQ5aTRuV1NQT0Q0
        aGcrK3lOeFR6UHRUSGVPSzZXbDJRRWMKLS0tIDFtU01STjQ2UTUvUk1rZ3o5SXhu
        RlZFTFd0L3NGUURyK1E3cjlrSlhRQmMKINN0fP8aKdaYASoJkRItf6F7WFeoRxFr
        zbBLlFPRZs4SoIkf8hgj6z/riOZHDLcsmAV1AuB87POABTw5DS+3Bg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17zks7jaqpljq6k8lgn939lfg6mqysf53r3n3l7e0j4tkhywyrqxqyc72x8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T08:19:00Z"
  mac: ENC[AES256_GCM,data:ERZQGyLiKvojAbYHDU+u0510vQ8+3M5bdc+xF7gfF2w4ZbQ7oosBx73M2xpfoWeaYQKO/xBd435I0QUcR0fZlZiZpiY7grPicDT2VFiWZi3Rhf2W442OWRnr3lXS16jBL47cqbFUPPSPs0RYpI9oE05l/zR2323T3f+7IbAg4Tk=,iv:QaBmIiWk1ybck+b4pBuQC8VMuXs7UfOBgrBeBDTpGGI=,tag:gnXMMVuY7gw3eCcseOVhjA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
