apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsSecret
metadata:
  name: cloudflare-dns-api-token
  namespace: cert-manager
spec:
  secrets:
    - name: cloudflare-dns-api-token
      stringData:
        token: ENC[AES256_GCM,data:06wtVYjd0fp4WemVAc2HRsI9a2YJFAUTdOQqO493xNnGeD+VzmrcuXP3zcqtneFyCvHIxOg=,iv:Qc5Q7faIfL9nuEjNZF5mMCAzN54kQfqlFhHF8aAiMZs=,tag:TSCpJKNwUP8LrvHm97E+vQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFE1WkIwUSBaNTdF
        c2ViY0NCd0RzVE14Z3lCS2hLUlBQQldRY1UrYjdSeEtPclVtTlNVCnRaTDEzNG1a
        T2RwRkpjVmRjR3NFREZTQzVKU0gxWC83MncyY0pVZ0djMUkKLS0tIHRUWUR2dzlq
        RmdoNjluSGNLVUVjbUtQT3hTYm9yeDNOdE5mNjhyR1RIaXMKKuM7VY02LKgXw+mg
        AzxnFZZ7FEI3fdIWnvi3nZzE4+1iCP3L6lppANAW931gWIhQgB93FRu+dJvt87u8
        18SH7w==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAcnmLrPeTJeKsasfU0qn4sP4lBNeOUgRG4iZDS8nyEo kid@vulkan
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE1Wa1kxQSBBVVph
        c3h0SkcyaWdMSWxLbnh4NGhkSWtvSXBDTWV1MnlkOHNOVXhiUVM4CjBRaGlRQzJF
        K3hLRGQ2Vm1nK1dBbjd4YkZaYUc3bFYvdmE1ZHU0TmkzVkkKLS0tIERQTlpOY0NP
        ajFrOHJMb1IycHZWN3dyamVIeFF5YThDaWZ2aCtxTEVSYlkKcraDE2iJmwwMSiVJ
        n+J7mw5SMnboPQPkzwROGN6jc3s4CGLEy18IParNxkr0gKO6W7N8BylhhaW6+D/m
        LbUivg==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHIM3nsk3HxvEcplSqwynh9V2NzlYdI10mrR746SiJZb kid@fw13
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCM21BMzB6WVdlSU4zKzV4
        SnJtNmxSR2hPZDM4VTV0bmpRaWZOSnZYVkVrCmwvb1l6NlZXTjRQaHlyUEg2dmt3
        YXNNbFZGSWhUc0l2TUExdG1RZTZDMnMKLS0tIENEcDAzODk4dysveTNleDh3WTZI
        dXVmei9RS0tHbGwyWHI2ckRJeTgvUjgKB4E/n7MnHom3smGc54N742slvp1da7wy
        5LpYeIT/VGaGvkLuBE+ptefLhbs89bjqPy0dVoBYZBIBrDcltwnjdw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17zks7jaqpljq6k8lgn939lfg6mqysf53r3n3l7e0j4tkhywyrqxqyc72x8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-17T18:41:10Z"
  mac: ENC[AES256_GCM,data:Eb3+kKyXuSpkQbZcUCipr6EoIGyIczyGp7C8zNKfzD5zVhGvH8RJBJXrVwXFBrGNStl+uiPteSEEUsWARJBSpgOdV6i+ymEBm6Pt08nYYC+0fWNFEh0YghZ/7RVPVsTsngf7sravqBDq+/Pu5TlKoJleFc3zjl/7krhv+0mIJ8c=,iv:WyEtkWsoVxxorXfXS9dj0VS9cDKuZLuUeMhW8VBwP8k=,tag:z08zzG6akw3Vc0dh7HZcMw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
