apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-api-token
  namespace: cloudflare-tunnel-system
spec:
  data:
    - remoteRef:
        key: cloudflared-tunnel-credentials/credentials/api-token
      secretKey: api-token
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-tunnel-api-token
