apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: cloudflare-tunnel-gateway-controller
    app.kubernetes.io/name: cloudflare-tunnel-gateway-controller
  name: cloudflare-tunnel-gateway-controller
  namespace: cloudflare-tunnel-system
