%YAML 1.1
---
creation_rules:
- key_groups:
  - age:
    - ssh-ed25519 
      AAAAC3NzaC1lZDI1NTE5AAAAIAcnmLrPeTJeKsasfU0qn4sP4lBNeOUgRG4iZDS8nyEo 
      kid@vulkan
    - ssh-ed25519 
      AAAAC3NzaC1lZDI1NTE5AAAAIHIM3nsk3HxvEcplSqwynh9V2NzlYdI10mrR746SiJZb 
      kid@fw13
    - ssh-ed25519 
      AAAAC3NzaC1lZDI1NTE5AAAAILkFKxaxcAS/tQuS8Gfk8xaHSLDAm1VCPHo8M7umUdVJ 
      root@node1
  path_regex: secrets/hosts/node1/.*
- key_groups:
  - age:
    - ssh-ed25519 
      AAAAC3NzaC1lZDI1NTE5AAAAIAcnmLrPeTJeKsasfU0qn4sP4lBNeOUgRG4iZDS8nyEo 
      kid@vulkan
    - ssh-ed25519 
      AAAAC3NzaC1lZDI1NTE5AAAAIHIM3nsk3HxvEcplSqwynh9V2NzlYdI10mrR746SiJZb 
      kid@fw13
    - age1crlwx4k0eaq666fa8dqpq3k9rhkm8qvwf3ewuum8s8hmrzrm55fsl3tk8h
    - ssh-ed25519 
      AAAAC3NzaC1lZDI1NTE5AAAAILkFKxaxcAS/tQuS8Gfk8xaHSLDAm1VCPHo8M7umUdVJ 
      root@node1
  path_regex: secrets/clusters/prd/.*
- key_groups:
  - age:
    - ssh-ed25519 
      AAAAC3NzaC1lZDI1NTE5AAAAIAcnmLrPeTJeKsasfU0qn4sP4lBNeOUgRG4iZDS8nyEo 
      kid@vulkan
    - ssh-ed25519 
      AAAAC3NzaC1lZDI1NTE5AAAAIHIM3nsk3HxvEcplSqwynh9V2NzlYdI10mrR746SiJZb 
      kid@fw13
    - age1crlwx4k0eaq666fa8dqpq3k9rhkm8qvwf3ewuum8s8hmrzrm55fsl3tk8h
  path_regex: manifests/prd/.*SopsSecret-.*\.ya?ml$
- key_groups:
  - age:
    - ssh-ed25519 
      AAAAC3NzaC1lZDI1NTE5AAAAIAcnmLrPeTJeKsasfU0qn4sP4lBNeOUgRG4iZDS8nyEo 
      kid@vulkan
    - ssh-ed25519 
      AAAAC3NzaC1lZDI1NTE5AAAAIHIM3nsk3HxvEcplSqwynh9V2NzlYdI10mrR746SiJZb 
      kid@fw13
stores:
  yaml:
    indent: 2
