keys:
  - &kid-vulkan ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAcnmLrPeTJeKsasfU0qn4sP4lBNeOUgRG4iZDS8nyEo kid@vulkan
  - &kid-fw13 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHIM3nsk3HxvEcplSqwynh9V2NzlYdI10mrR746SiJZb kid@fw13

defaults: &defaults
  key_groups:
    - age:
        - *kid-vulkan
        - *kid-fw13

creation_rules:
  - path_regex: clusters/lab/.+.sops.ya?ml
    unencrypted_regex: "^(apiVersion|metadata|kind|type)$"
    key_groups:
      - age:
          - age146tlu0sxyhruen9k800szpfr0na5mrm3udl4qqkpx7lp7msw7fssz55qaj
          - *kid-vulkan
          - *kid-fw13
  - <<: *defaults

stores:
  yaml:
    indent: 2
