keys:
  - &kid-vulkan ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAcnmLrPeTJeKsasfU0qn4sP4lBNeOUgRG4iZDS8nyEo kid@vulkan
  - &kid-fw13 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHIM3nsk3HxvEcplSqwynh9V2NzlYdI10mrR746SiJZb kid@fw13

defaults: &defaults
  key_groups:
    - age:
        - *kid-vulkan
        - *kid-fw13

creation_rules:
  - <<: *defaults

stores:
  yaml:
    indent: 2
