---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name mikrotik-credentials
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: *mikrotik-credentials
    creationPolicy: Owner

  data:
    - secretKey: endpoint
      remoteRef:
        key: rb5009 - external-dns
        property: endpoint
    - secretKey: insecure
      remoteRef:
        key: rb5009 - external-dns
        property: insecure
    - secretKey: username
      remoteRef:
        key: rb5009 - external-dns
        property: username
    - secretKey: password
      remoteRef:
        key: rb5009 - external-dns
        property: password
