---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../kubernetes/apps/storage-system/
  - ./storageclasses.yaml
  - ./volumesnapshotclass.yaml

# patches:
#   - target:
#       group: kustomize.toolkit.fluxcd.io
#       version: v1
#       kind: Kustomization
#       name: piraeus-operator
#       namespace: storage-system
#     patch: |-
#       $patch: delete
#       apiVersion: kustomize.toolkit.fluxcd.io/v1
#       kind: Kustomization
#       metadata:
#         name: piraeus-operator
#         namespace: storage-system
