---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-downloads
spec:
  storageClassName: ${APP_STORAGECLASS}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
