apiVersion: batch/v1
kind: CronJob
metadata:
  name: openbao-unseal
  namespace: openbao
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - sh
                - -c
                - bao operator unseal "$(cat /unseal/unsealKey)"
              env:
                - name: BAO_ADDR
                  value: http://openbao.openbao.svc:8200
              image: openbao/openbao:2.6.2
              name: unseal
              volumeMounts:
                - mountPath: /unseal
                  name: unseal
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: unseal
              secret:
                secretName: openbao-unseal
  schedule: '* * * * *'
