apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-tls
  namespace: openbao
spec:
  dataFrom:
    - extract:
        decodingStrategy: Base64
        key: wildcard-tls
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: openbao-tls
    template:
      type: kubernetes.io/tls
