apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-unseal
  namespace: openbao
spec:
  data:
    - remoteRef:
        key: OpenBao - unseal key
        property: unsealKey
      secretKey: unsealKey
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: openbao-unseal
