apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-openbao-0
  namespace: openbao
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    apiGroup: kopiur.home-operations.com
    kind: Restore
    name: openbao-data
  resources:
    requests:
      storage: 10Gi
  storageClassName: miroir
