apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: openbao-init-output
  namespace: openbao
spec:
  data:
    - match:
        remoteRef:
          property: unsealKey
          remoteKey: OpenBao - unseal key
        secretKey: unsealKey
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: onepassword
  selector:
    secret:
      name: openbao-init-output
