apiVersion: kopiur.home-operations.com/v1alpha1
kind: Restore
metadata:
  name: openbao-data
  namespace: openbao
spec:
  credentialProjection:
    enabled: true
  policy:
    onMissingSnapshot: Continue
  source:
    fromPolicy:
      name: openbao-data
      offset: 0
  target:
    populator: {}
