apiVersion: v1
kind: Service
metadata:
  annotations:
    io.cilium/lb-ipam-ips: 10.0.42.10
  labels:
    app.kubernetes.io/instance: openbao
    app.kubernetes.io/name: openbao
  name: openbao
  namespace: openbao
spec:
  externalTrafficPolicy: Cluster
  ports:
    - appProtocol: HTTP
      name: http
      port: 8200
      targetPort: 8200
    - name: https-internal
      port: 8201
      targetPort: 8201
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: openbao
    app.kubernetes.io/name: openbao
    component: server
  type: LoadBalancer
