apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: openbao.kidibox.net
  name: openbao-external
  namespace: openbao
spec:
  ports:
    - name: https
      port: 8200
      targetPort: 8200
  selector:
    app.kubernetes.io/name: openbao
    component: server
  type: LoadBalancer
