---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: telegram
spec:
  route:
    receiver: telegram
    group_by:
      - alertname
      - cluster
      - namespace
      - severity
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: blackhole
        matchers:
          - alertname = "Watchdog"
      - receiver: blackhole
        matchers:
          - alertname = "InfoInhibitor"
  inhibit_rules:
    - source_matchers:
        - severity = "critical"
      target_matchers:
        - severity =~ "warning|info"
      equal:
        - cluster
        - namespace
        - alertname
    - source_matchers:
        - severity = "warning"
      target_matchers:
        - severity = "info"
      equal:
        - cluster
        - namespace
        - alertname
  receivers:
    - name: blackhole
    - name: telegram
      telegram_configs:
        - bot_token:
            name: alertmanager-telegram-secrets
            key: TELEGRAM_BOT_TOKEN
          chat_id: ${TELEGRAM_CHAT_ID:=0}
          message: |-
            <b>{{ .Status }}</b>: <b>{{ .CommonLabels.alertname }}</b>
            <b>Severity:</b> {{ .CommonLabels.severity }}
            <b>Cluster:</b> {{ .CommonLabels.cluster }}{{ if .CommonLabels.namespace }}
            <b>Namespace:</b> {{ .CommonLabels.namespace }}{{ end }}
            <b>Alerts:</b> {{ len .Alerts }}

            {{ range .Alerts }}{{ if ne .Annotations.summary "" }}{{ .Annotations.summary }}{{ else if ne .Annotations.description "" }}{{ .Annotations.description }}{{ else if ne .Annotations.message "" }}{{ .Annotations.message }}{{ else }}Alert description not available{{ end }}{{ if ne .Annotations.runbook_url "" }}
            <b>Runbook:</b> {{ .Annotations.runbook_url }}{{ end }}{{ if gt (len .Labels.SortedPairs) 0 }}
            {{ range .Labels.SortedPairs }}<b>{{ .Name }}:</b> {{ .Value }}
            {{ end }}{{ end }}

            {{ end }}
          parse_mode: HTML
          send_resolved: true
