---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  interval: 10m0s
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-values
        optional: false
      - kind: Secret
        name: namespace-secrets
        optional: true
  patches:
    - patch: |
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: all
        spec:
          postBuild:
            substituteFrom:
              - kind: ConfigMap
                name: cluster-values
                optional: false
              - kind: Secret
                name: namespace-secrets
                optional: true
      target:
        kind: Kustomization
        labelSelector: home-ops.io/skip-cluster-values-substitute-from!=true
  path: ./clusters/dev/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
