---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: "${APP}-volsync-secret"
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "s3:{{ .endpoint }}/volsync/${APP}"
        RESTIC_PASSWORD: "{{ .restic_password }}"
        AWS_ACCESS_KEY_ID: "{{ .username }}"
        AWS_SECRET_ACCESS_KEY: "{{ .credential }}"
  dataFrom:
    - extract:
        key: Cloudflare R2 Backups
