---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-server
spec:
  chartRef:
    kind: OCIRepository
    name: nfs-server
  interval: 1h
  values:
    controllers:
      nfs-server:
        strategy: RollingUpdate
        pod:
          priorityClassName: nfs-critical
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsNonRoot: false
            seccompProfile: { type: Unconfined }
        containers:
          nfs-server:
            image:
              # Only latest tag is published and digest is overwritten each update so don't pin digest
              # e.g. node boots after update, latest@sha no longer exists, new update not merged == no nfs
              repository: quay.io/aminvakil/alpine-nfs-server
              tag: latest
            env:
              EXPORTS_MOUNTED: true
              NFS_THREADS: 128
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - sh
                      - -c
                      - "showmount -e localhost | grep -q /export"
              readiness: &probes
                enabled: true
                type: TCP
                port: 2049
                spec:
                  periodSeconds: 3
                  timeoutSeconds: 1
                  failureThreshold: 2
                  successThreshold: 1
              liveness: *probes
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
              privileged: true
    service:
      nfs-server:
        controller: nfs-server
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          lbipam.cilium.io/ips: 10.0.42.20
          coredns.io/hostname: nfs.${APP_DOMAIN}
        ports:
          nfs:
            port: 2049
    persistence:
      exports:
        type: configMap
        name: nfs-exports
        globalMounts:
          - path: /etc/exports
            subPath: exports
      fake-export:
        type: emptyDir
        globalMounts:
          - path: /export
      media:
        type: persistentVolumeClaim
        existingClaim: storage-media-talos1-zfs
        globalMounts:
          - path: /export/media
