---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.35.2-standalone-strict/priorityclass-scheduling-v1.json
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: nfs-critical
value: 100000000
globalDefault: false
description: "Ensure NFS is evicted last."
