apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-crds
  namespace: argocd
spec:
  destination:
    namespace: gateway-api-crds
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/prd/gateway-api-crds
    repoURL: https://github.com/kid/home-ops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
