apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-external-dns-token
  namespace: external-dns
spec:
  data:
    - remoteRef:
        key: cloudflare-external-dns-token/credentials/token
      secretKey: token
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-external-dns-token
