---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: local-path-provisioner
  values:
    storageClass:
      create: true
      name: local-path
      defaultClass: false
      reclaimPolicy: Delete
      volumeBindingMode: WaitForFirstConsumer
