---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-values
data:
  NETWORK_POD_CIDR: ${NETWORK_POD_CIDR}
  NETWORK_SVC_CIDR: ${NETWORK_SVC_CIDR}
  NETWORK_LB_CIDR: ${NETWORK_LB_CIDR}
  NETWORK_ROUTER_NAME: ${NETWORK_ROUTER_NAME}
  NETWORK_ROUTER_IP: ${NETWORK_ROUTER_IP}
  NETWORK_API_SERVER_IP: ${NETWORK_API_SERVER_IP}
  APP_DOMAIN: ${APP_DOMAIN}
  APP_STORAGECLASS: ${APP_STORAGECLASS}
  APP_SNAPSHOTCLASS: ${APP_SNAPSHOTCLASS}
