---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echo
spec:
  dependsOn:
    - name: envoy-gateway
    - name: envoy-gateway-resources
    - name: prometheus-operator-crds
      namespace: observability
  interval: 1h
  path: ./kubernetes/apps/network-system/echo/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network-system
  wait: false
