apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: sops-operator
    app.kubernetes.io/name: sops-operator
  name: sops-operator-metrics
  namespace: sops-operator
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/instance: sops-operator
    app.kubernetes.io/name: sops-operator
  type: ClusterIP
