---
machine:
  type: controlplane
  install:
    disk: /home/vda
    wipe: true
  logging:
    destinations:
      - endpoint: tcp://127.0.0.1:15140/
        format: json_lines
        extraTags:
          talos_node_name: talos1
          talos_node_ip: 10.0.40.201
---
apiVersion: v1alpha1
kind: HostnameConfig
$patch: delete
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: talos1
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  minSize: 10GiB
  maxSize: 10GiB
  grow: false
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-storage
provisioning:
  diskSelector:
    match: "system_disk"
  minSize: 10GB
  maxSize: 100GB
