---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../kubernetes/apps/virtualization-system/kubevirt/app
patches:
  - target:
      group: kubevirt.io
      version: v1
      kind: KubeVirt
      name: kubevirt
      namespace: kubevirt
    patch: |-
      - op: add
        path: /spec/configuration/permittedHostDevices
        value:
          pciHostDevices:
            - pciVendorSelector: "1000:00e6"
              resourceName: devices.kubevirt.io/sas-hba
