---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victorialogs
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  plugins:
    - name: victoriametrics-logs-datasource
      version: 0.26.3
  datasource:
    name: VictoriaLogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: &vmauthUrl http://victoria-logs-vl-vmauth.observability.svc.cluster.local:8427
    isDefault: false
    jsonData: {}
