# Shared nixidy defaults, injected into every cluster's k8s-manifests scope.
# Not a collector itself — modules/den/policies/cluster.nix's
# cluster-to-nixidy policy assembles this aspect's content together with
# each app aspect's (modules/den/aspects/kubernetes/*/default.nix) into the real
# nixidy environment.
_:
let
  nixidyDefaultsAspect = {
    name = "nixidy/defaults";
    k8s-manifests =
      { cluster, environment, ... }:
      { lib, config, ... }:
      let
        # kube-system/default are pre-existing, cluster-critical namespaces —
        # never let an app's own createNamespace = true put them under
        # ArgoCD's "apps" root Application.
        systemNamespaces = [
          "kube-system"
          "default"
        ];
        # Every app's own namespace is created here instead of in its own
        # manifest set, so two apps sharing a namespace (e.g. cert-manager +
        # trust-manager) don't each end up owning the same object as a
        # "shared resource" in ArgoCD. Apps no longer set createNamespace
        # themselves — this replaces nixidy's own per-app handling of it.
        namespacesToCreate = lib.unique (
          lib.filter (ns: !(builtins.elem ns systemNamespaces)) (
            map (app: app.namespace) (lib.attrValues config.applications)
          )
        );
      in
      {
        # den's collision-validator writes to config.warnings; nixidy's own
        # module system doesn't declare that NixOS-ism by default.
        options.warnings = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          default = [ ];
        };

        config.applications.${config.nixidy.appOfApps.name}.resources.namespaces =
          lib.genAttrs namespacesToCreate
            (_: {
              metadata.annotations."argocd.argoproj.io/sync-options" = "Prune=false";
            });

        config.nixidy = {
          env = lib.mkDefault "${environment.name}-${cluster.name}";
          target = {
            repository = lib.mkDefault cluster.nixidy.repository;
            branch = lib.mkDefault cluster.nixidy.branch;
            rootPath = lib.mkDefault cluster.nixidy.rootPath;
          };
          bootstrapManifest.enable = true;
          extraFiles."README.md".text = "Generated by nixidy — do not edit by hand.\n";
          # syncOptions has no nixidy.defaults hook (unlike autoSync), so
          # apply it to every applications.<name> via applicationImports.
          applicationImports = [
            (
              { lib, ... }:
              {
                syncPolicy.syncOptions.serverSideApply = lib.mkDefault true;
                # Without a retry, one resource failing to apply (e.g. an
                # admission webhook that isn't serving yet) stalls the sync.
                syncPolicy.retry = lib.mkDefault {
                  limit = 10;
                  backoff = {
                    duration = "10s";
                    factor = 2;
                    maxDuration = "3m";
                  };
                };
              }
            )
          ];
          defaults = {
            syncPolicy.autoSync = {
              enable = true;
              prune = true;
              selfHeal = true;
            };
            helm.transformer = map (
              lib.kube.removeLabels [
                "app.kubernetes.io/managed-by"
                "app.kubernetes.io/version"
                "helm.sh/chart"
              ]
            );
          };
        };
      };
  };
in
{
  den.schema.cluster.includes = [ nixidyDefaultsAspect ];
}
