# Shared nixidy defaults, injected into every cluster's k8s-manifests scope.
# Not a collector itself — modules/den/policies/cluster.nix's
# cluster-to-nixidy policy assembles this aspect's content together with
# each app aspect's (modules/den/aspects/kubernetes/*/default.nix) into the real
# nixidy environment.
_:
let
  nixidyDefaultsAspect = {
    name = "nixidy/defaults";
    k8s-manifests =
      { cluster, environment, ... }:
      { lib, ... }:
      {
        # den's collision-validator writes to config.warnings; nixidy's own
        # module system doesn't declare that NixOS-ism by default.
        options.warnings = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          default = [ ];
        };

        config.nixidy = {
          env = lib.mkDefault "${environment.name}-${cluster.name}";
          target = {
            repository = lib.mkDefault cluster.nixidy.repository;
            branch = lib.mkDefault cluster.nixidy.branch;
            rootPath = lib.mkDefault cluster.nixidy.rootPath;
          };
          bootstrapManifest.enable = true;
          extraFiles."README.md".text = "Generated by nixidy — do not edit by hand.\n";
          # syncOptions has no nixidy.defaults hook (unlike autoSync), so
          # apply it to every applications.<name> via applicationImports.
          applicationImports = [
            (
              { lib, ... }:
              {
                syncPolicy.syncOptions.serverSideApply = lib.mkDefault true;
              }
            )
          ];
          defaults = {
            syncPolicy.autoSync = {
              enable = true;
              prune = true;
              selfHeal = true;
            };
            helm.transformer = map (
              lib.kube.removeLabels [
                "app.kubernetes.io/managed-by"
                "app.kubernetes.io/version"
                "helm.sh/chart"
              ]
            );
          };
        };
      };
  };
in
{
  den.schema.cluster.includes = [ nixidyDefaultsAspect ];
}
