---

clusterName: metal
endpoint: https://10.0.40.200:6443

target: metal

talosVersion: v1.12.6
kubernetesVersion: v1.35.0

nodes:
  - ipAddress: 10.0.40.200
    hostname: talos0
    role: controlplane
    patches:
      - ./nodes/talos0.yaml
      - ./patches/zfs.yaml
  - ipAddress: 10.0.40.201
    hostname: talos1
    role: worker
    target: cloud
    platform: nocloud
    patches:
      - ./nodes/talos1.yaml
      - ./patches/zfs.yaml

patches:
  common:
    - ./patches/files.yaml
    - ./patches/host-dns.yaml

  controlplane:
    - ./patches/additional-sans.yaml
    - ./patches/cilium.yaml
    - ./patches/cluster-discovery.yaml
    - ./patches/schedule-on-controlplane.yaml
