apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: kopiur-r2
  namespace: kopiur-system
spec:
  data:
    - remoteRef:
        key: kopiur-r2-credentials/credentials/access-key-id
      secretKey: AWS_ACCESS_KEY_ID
    - remoteRef:
        key: kopiur-r2-credentials/credentials/secret-access-key
      secretKey: AWS_SECRET_ACCESS_KEY
    - remoteRef:
        key: kopiur-r2-credentials/credentials/repository-password
      secretKey: KOPIA_PASSWORD
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kopiur-r2
