apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: kopiur-r2
  namespace: kopiur-system
spec:
  data:
    - remoteRef:
        key: kopiur - R2 credentials
        property: accessKeyId
      secretKey: AWS_ACCESS_KEY_ID
    - remoteRef:
        key: kopiur - R2 credentials
        property: secretAccessKey
      secretKey: AWS_SECRET_ACCESS_KEY
    - remoteRef:
        key: kopiur - R2 credentials
        property: repositoryPassword
      secretKey: KOPIA_PASSWORD
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kopiur-r2
