apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: kopiur
    app.kubernetes.io/name: kopiur
    app.kubernetes.io/part-of: kopiur
  name: kopiur-webhook
  namespace: kopiur-system
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: kopiur
    app.kubernetes.io/name: kopiur
  type: ClusterIP
