# Generates docs/clusters/<name>.md from den.clusters, so the kubectl commands take their server name,
# issuer and client ID from the values the cluster is configured with (methods.kubeLogin, set in
# modules/den/aspects/kubernetes/apiserver/default.nix). A cluster without kubeLogin gets no doc.
# Generated output, like .sops.yaml and manifests/**: checks.docs fails when it is stale.
{
  config,
  lib,
  self,
  ...
}:
let
  clusters = lib.filterAttrs (_: cluster: cluster.methods ? kubeLogin) config.den.clusters;

  allHosts = lib.foldl' (acc: system: acc // (config.den.hosts.${system} or { })) { } config.systems;

  # The first host of the cluster (host.k3s.clusterName), at its address on the cluster network.
  nodeAddress =
    name:
    let
      members = builtins.filter (host: (allHosts.${host}.k3s.clusterName or null) == name) (
        builtins.attrNames allHosts
      );
    in
    config.den.devices."${builtins.head members}-k3s".address;

  render =
    name: cluster:
    let
      login = cluster.methods.kubeLogin;
      vault = cluster.secrets.onepasswordVault;
      node = nodeAddress name;
    in
    ''
      # ${name}: kubectl login

      Generated by `nix run .#write-docs` from `den.clusters.${name}`. Do not edit by hand.

      kubectl logs in through Authelia (${login.issuerUrl}) with [kubelogin](https://github.com/int128/kubelogin),
      as in [Authelia's kubelogin page](https://www.authelia.com/integration/openid-connect/clients/kubelogin/).
      The Authelia group `${login.group}` gets `cluster-admin`.

      ## Before you start

      - The kubelogin plugin on `PATH`: package `kubelogin-oidc`, binary `kubectl-oidc_login`.
      - The 1Password CLI, signed in, with access to the `${vault}` vault.
      - SSH access to the node `${node}`, to fetch the certificate authority of the API server.

      ## Set up kubectl

      ```sh
      ssh ${node} sudo cat /var/lib/rancher/k3s/server/tls/server-ca.crt > /tmp/${name}-ca.crt

      kubectl config set-cluster ${name} \
        --server=https://${login.server}:6443 \
        --certificate-authority=/tmp/${name}-ca.crt \
        --embed-certs=true

      kubectl config set-credentials ${name}-oidc \
        --exec-api-version=client.authentication.k8s.io/v1 \
        --exec-interactive-mode=Never \
        --exec-command=kubectl \
        --exec-arg=oidc-login \
        --exec-arg=get-token \
        --exec-arg=--oidc-issuer-url=${login.issuerUrl} \
        --exec-arg=--oidc-client-id=${login.clientId} \
        --exec-arg=--oidc-client-secret="$(op read 'op://${vault}/authelia/secrets/kubelogin-client-secret')" \
        --exec-arg=--oidc-extra-scope=groups \
        --exec-arg=--oidc-extra-scope=offline_access

      kubectl config set-context ${name} --cluster=${name} --user=${name}-oidc
      kubectl config use-context ${name}
      ```

      ## Check

      ```sh
      kubectl auth whoami
      kubectl get nodes
      ```

      The first command opens your browser for Authelia. `whoami` lists the group `${login.group}`.

      ## Notes

      - The client secret is stored in your kubeconfig, as an argument of the plugin.
      - If Authelia is down, use the admin kubeconfig on the node: `ssh ${node} sudo cat /etc/rancher/k3s/k3s.yaml`.
    '';
in
{
  perSystem =
    { pkgs, config, ... }:
    let
      docsDir = pkgs.linkFarm "cluster-docs" (
        lib.mapAttrsToList (name: cluster: {
          name = "${name}.md";
          path = pkgs.writeText "${name}.md" (render name cluster);
        }) clusters
      );
    in
    {
      packages.write-docs = pkgs.writeShellApplication {
        name = "write-docs";
        runtimeInputs = [ pkgs.rsync ];
        text = ''
          mkdir -p docs/clusters
          rsync -rL --delete --chmod=D755,F644 "${docsDir}/" docs/clusters/
          echo "==> Wrote docs/clusters"
        '';
      };

      apps.write-docs = {
        type = "app";
        program = "${config.packages.write-docs}/bin/write-docs";
      };

      checks.docs = pkgs.runCommandLocal "docs-check" { nativeBuildInputs = [ pkgs.diffutils ]; } ''
        if ! diff -r "${self}/docs/clusters" "${docsDir}"; then
          echo "docs/clusters is stale — run: nix run .#write-docs" >&2
          exit 1
        fi
        touch $out
      '';
    };
}
