apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-tls
  namespace: envoy-gateway-system
spec:
  dnsNames:
    - '*.dev.kidibox.net'
    - dev.kidibox.net
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: apps-tls
