---
machine:
  type: worker
  install:
    disk: /home/vda
    wipe: true
---
apiVersion: v1alpha1
kind: HostnameConfig
$patch: delete
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: talos1
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  minSize: 10GiB
  maxSize: 10GiB
  grow: false
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-storage
provisioning:
  diskSelector:
    match: "system_disk"
  minSize: 10GB
  maxSize: 100GB
