---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-ops-runner
spec:
  chartRef:
    kind: OCIRepository
    name: home-ops-runner
  interval: 1h
  values:
    githubConfigUrl: https://github.com/kid/home-ops
    githubConfigSecret: home-ops-runner-auth-secret
    runnerScaleSetName: home-ops
    minRunners: 0
    maxRunners: 3
    scaleSetLabels:
      - home-ops
      - kubernetes
    controllerServiceAccount:
      namespace: actions-runner-system
      name: actions-runner-controller-gha-rs-controller
    containerMode:
      type: kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes:
          - ReadWriteOnce
        storageClassName: ${APP_STORAGECLASS}
        resources:
          requests:
            storage: 10Gi
      kubernetesModeAdditionalRoleRules:
        - apiGroups:
            - ""
          resources:
            - pods/attach
            - pods/portforward
          verbs:
            - create
            - get
    template:
      spec:
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
