---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ks.yaml
components:
  - ../../../components/ks-base
  - ../../../components/ks-external-secrets
  - ../../../components/ks-volsync
  - ../../../components/ks-nfs
