---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword-connect-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ${ONEPASSWORD_STORE}
  target:
    name: onepassword-connect-credentials-secret
    template:
      data:
        1password-credentials.json: '{{ .OP_SESSION_JSON }}'
  dataFrom:
    - extract:
        key: onepassword - "${CLUSTER_NAME}"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword-connect-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ${ONEPASSWORD_STORE}
  target:
    name: onepassword-connect-token-secret
    template:
      data:
        token: '{{ .OP_CONNECT_TOKEN }}'
  dataFrom:
    - extract:
        key: onepassword - "${CLUSTER_NAME}"
