---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mqtt
spec:
  chartRef:
    kind: OCIRepository
    name: mqtt
  interval: 1h
  values:
    controllers:
      mqtt:
        type: statefulset
        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.22
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
        statefulset:
          volumeClaimTemplates:
            - name: config
              storageClass: linstor-zfs-virtio
              accessMode: ReadWriteOnce
              size: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        type: ClusterIP
        ports:
          mqtt:
            port: 8883
    configMaps:
      config:
        data:
          mosquitto.conf: |-
            allow_anonymous false
            per_listener_settings true
            listener 8883
            cafile /mosquitto/certs/ca.crt
            certfile /mosquitto/certs/tls.crt
            keyfile /mosquitto/certs/tls.key
            require_certificate true
            use_identity_as_username true
            persistence true
            persistence_location /config
    persistence:
      config-file:
        type: configMap
        identifier: config
        globalMounts:
          - path: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
      certs:
        type: secret
        name: mqtt-tls
        globalMounts:
          - path: /mosquitto/certs
            readOnly: true
