apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: headlamp-oidc
  namespace: headlamp
spec:
  data:
    - remoteRef:
        key: authelia/secrets/kubelogin-client-secret
      secretKey: clientSecret
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: headlamp-oidc
    template:
      data:
        OIDC_CALLBACK_URL: https://headlamp.kidibox.net/oidc-callback
        OIDC_CLIENT_ID: kube_login
        OIDC_CLIENT_SECRET: '{{ .clientSecret }}'
        OIDC_ISSUER_URL: https://auth.kidibox.net
        OIDC_SCOPES: profile,email,groups,offline_access
