---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automaton

components:
  - ../../components/cluster-values
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./mqtt/ks.yaml
  # - ./frigate/ks.yaml
