---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../kubernetes/apps/external-secrets/
  - ../../../kubernetes/apps/flux-system/
  - ../../../kubernetes/apps/kube-system/
  - ../../../kubernetes/apps/network-system/
  - ../../../kubernetes/apps/observability/
  - ./storage-system/
