---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nfs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nfs
    spec:
      nodeSelector:
        kubernetes.io/hostname: talos0
      containers:
        - name: nfs
          image: quay.io/aminvakil/alpine-nfs-server:latest
          envFrom:
            - configMapRef:
                name: nfs
          ports:
            - name: nfs
              containerPort: 2049
              protocol: TCP
          securityContext:
            privileged: true
          volumeMounts:
            - name: nfsshare
              mountPath: /nfsshare
      volumes:
        - name: nfsshare
          hostPath:
            path: /var/mnt/tank
            type: Directory
