---
apiVersion: v1
kind: Service
metadata:
  name: nfs
  annotations:
    external-dns.alpha.kubernetes.io/hostname: tank.nfs.${INTERNAL_DOMAIN}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nfs
  ports:
    - name: nfs
      port: 2049
      protocol: TCP
      targetPort: nfs
