---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flux-rules
spec:
  groups:
    - name: flux
      rules:
        - alert: FluxBranchOverrideActive
          annotations:
            summary: Flux is pinned to a non-default branch by flux-system/cluster-branch-override.
          expr: kube_configmap_info{namespace="flux-system",configmap="cluster-branch-override"} == 1
          for: 10m
          labels:
            severity: warning
