---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &release victoria-logs
spec:
  releaseName: *release
  chartRef:
    kind: OCIRepository
    name: victoria-logs-single
  interval: 1h
  targetNamespace: observability
  values:
    nameOverride: vl
    server:
      replicaCount: 1
      retentionPeriod: 30d
      persistentVolume:
        enabled: true
        existingClaim: ${VOLSYNC_PVC}
        mountPath: /storage
      route:
        enabled: true
        extraRules:
          - matches:
              - path:
                  type: Exact
                  value: /
            filters:
              - type: RequestRedirect
                requestRedirect:
                  path:
                    type: ReplaceFullPath
                    replaceFullPath: /select/vmui/
                  statusCode: 302
        hostnames:
          - logs.${APP_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network-system
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      resources:
        requests:
          cpu: 300m
          memory: 1Gi
        limits:
          memory: 2Gi
