---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cdi-upstream
spec:
  interval: 1h
  timeout: 2m
  url: https://github.com/JJGadgets/kubevirt-flux
  ref:
    branch: cdi-v1.63.1
