---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name mikrotik-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ${ONEPASSWORD_STORE}

  dataFrom:
    - extract:
        key: rb5009 - external-dns

  target:
    name: *name
