apiVersion: v1
data:
  policy.csv: g, admins, role:admin
  policy.default: role:admin
  scopes: '[groups]'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
