apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-webhook
  namespace: argocd
spec:
  data:
    - remoteRef:
        key: argocd/secrets/github-webhook-secret
      secretKey: githubWebhookSecret
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Merge
    name: argocd-secret
    template:
      data:
        webhook.github.secret: '{{ .githubWebhookSecret }}'
