apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: argocd-oidc
  namespace: argocd
spec:
  data:
    - remoteRef:
        key: authelia/secrets/argocd-client-secret
      secretKey: clientSecret
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: argocd-oidc
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
