---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-telegram-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: alertmanager-telegram-secrets
    template:
      data:
        TELEGRAM_BOT_TOKEN: "{{ .TELEGRAM_BOT_TOKEN }}"
        TELEGRAM_CHAT_ID: "{{ .TELEGRAM_CHAT_ID }}"
  dataFrom:
    - extract:
        key: ${CLUSTER_NAME}.telegram.bot
