---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

components:
  - ../../components/cluster-values
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./grafana/ks.app.yaml
  - ./grafana/ks.resources.yaml
  - ./mikrotik-exporter/ks.app.yaml
  - ./victoria-metrics/ks.app.yaml
  - ./victoria-metrics-rules/ks.app.yaml
  - ./victoria-logs/ks.app.yaml
  - ./victoria-logs-collector/ks.app.yaml
