apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: kube-api
  namespace: default
spec:
  hostnames:
    - kube.kidibox.net
  parentRefs:
    - name: apps
      namespace: envoy-gateway-system
      sectionName: kube-api
  rules:
    - backendRefs:
        - name: kubernetes
          port: 443
