apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: wildcard-tls-import
  namespace: cert-manager
spec:
  dataFrom:
    - extract:
        decodingStrategy: Base64
        key: wildcard-tls
  refreshPolicy: CreatedOnce
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Orphan
    name: wildcard-tls
    template:
      metadata:
        annotations:
          cert-manager.io/alt-names: '*.kidibox.net,kidibox.net'
          cert-manager.io/certificate-name: wildcard
          cert-manager.io/common-name: ""
          cert-manager.io/ip-sans: ""
          cert-manager.io/issuer-group: ""
          cert-manager.io/issuer-kind: ClusterIssuer
          cert-manager.io/issuer-name: letsencrypt-prod
          cert-manager.io/uri-sans: ""
        labels:
          controller.cert-manager.io/fao: "true"
      type: kubernetes.io/tls
