apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns-api-token
  namespace: cert-manager
spec:
  data:
    - remoteRef:
        key: cert-manager/cloudflare-dns-api-token
        property: token
      secretKey: token
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    creationPolicy: Owner
