apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: wildcard-tls
  namespace: cert-manager
spec:
  data:
    - match:
        remoteRef:
          property: tls.crt
          remoteKey: wildcard-tls
        secretKey: tls.crt
    - match:
        remoteRef:
          property: tls.key
          remoteKey: wildcard-tls
        secretKey: tls.key
  refreshInterval: 1h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: onepassword
  selector:
    secret:
      name: wildcard-tls
  template:
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
