apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsSecret
metadata:
  name: cloudflare-dns-api-token
  namespace: cert-manager
spec:
  secrets:
    - name: cloudflare-dns-api-token
      stringData:
        token: ENC[AES256_GCM,data:hQzD38Hx8LeIb8zGwOpILWKFNk89o5vazC0y,iv:XVZXDEinyf484QxrBFM62yyyoBpNk30D90WhG7TKZuo=,tag:McKm0itp4fqzySNfb05ygQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFE1WkIwUSA5WnlT
        NUE5aE5uV2QvM2V5Q2t4bFpMMHNKL1FkcG9acUdtdjY4aHczQWhBCnZJcEZuUGVt
        d0s3b21VNWMrWWxDbk1mZXYwVWlkOHVLa09wdDhaaVdxUmcKLS0tIGZNaFFXUE1P
        UXIxaWtLOFJqMk5aeURJUkdBQm4yTkFINVVCRGcyOENDMU0Kcjf/yljRtARGRS2F
        lwaFrKgBVsgXkrlELE7N/qsOm60tcxIUrNAGci2DvKTgiwbSzopxnjHp11sR9v1u
        +yqQGg==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAcnmLrPeTJeKsasfU0qn4sP4lBNeOUgRG4iZDS8nyEo kid@vulkan
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE1Wa1kxQSBjd01M
        OFphdStaVGp1VzZtSi9xamFZVXJQMzZXQ2VQWEsyS0pUNEY0ZHg4CkEvUWoxeFJt
        MmZsWC9DS28rUmMybGxVL2xaTEVtbUF5cmNGdnRHcVRCRW8KLS0tIGYrMTlFbXZr
        YU4wMkV3dHF0SjlZZENSbXRITDh1bmVMU3ZGMFY3TERjdUEKu6DSfMkV9m/5yTq4
        kEPklIGO9IbiPjPQDu2epK1+qmOzqvCt7WPOoafLEtahnGOElAKWYHCpbaACNLwu
        JoAXkQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHIM3nsk3HxvEcplSqwynh9V2NzlYdI10mrR746SiJZb kid@fw13
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrR2crZTU2eUp6MnJLOEY0
        ZmZNTit3dXNET2JhOHA2QzYxUTdoWnY4TFNzCjdUaitZTjZ2QWlKbWxpalJqM0pQ
        azBCQ09SWFNGWUs0MFhKUGJhVlFNNE0KLS0tIGs3M3EzdlRJbkpiRmtQZFdINTVp
        NHhJTTFGN2xkSTM3ZHFhL3R1dWdsUm8K2UJVwI5mfh33plbLL/AUockAkhD77Aa4
        EiVORvGk06f3XOmaoCdXk5li3Kqzzg05XZ8CyxsAtEoLeWYocdKTLQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1crlwx4k0eaq666fa8dqpq3k9rhkm8qvwf3ewuum8s8hmrzrm55fsl3tk8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-18T15:46:40Z"
  mac: ENC[AES256_GCM,data:0IWfzMejoGR/COhBuoF6zhyQylEq+2w86HQcJaDAu8H+YFf8TKqRTGF82ImJeZT7FY5NRJyWbCZGkDxsj5e/LgB2w7neVEBel29VgPXr7KIToS/NmQpPhHn+Vp88YwdQjE8bGTFzga1oMpL+F4QAGTzIeBhEhHiwSacmefJfhwQ=,iv:ixsboKEr2miR1oOBHPwMz4mx+DjKqTsbQ5ZybxJxNIg=,tag:DpkffL2Up6J6ba6+wQEOSA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
