apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsSecret
metadata:
  name: cloudflare-dns-api-token
  namespace: cert-manager
spec:
  secrets:
    - name: cloudflare-dns-api-token
      stringData:
        token: ENC[AES256_GCM,data:CGbhENvhemnBs2Sk88XBoMRHFGMQQPPv/vWJWavruBNiK+EWWiw/inClNzsdsnAYJ1GBE8U=,iv:K8tRm5p2u2/9s6eRecqGPzEky/8GKe28JZbBz0Le6kU=,tag:ExdSyiOGzmBh4NFT0JeNHA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFE1WkIwUSAzZUJi
        T25QQ3Awb1EyL0xZMXBxbUpRSndrV0J1QkQ0QWVtVWdUcEZ0UnpNCk9xYTZrc2oz
        UjMzS1ltZWM3bXpMT0h6dGd3WktvRHhaQVRxazE0VlZTTEEKLS0tIDdDaHBwcGEx
        UUVTQU5Ec0J4U29CWTlsSEhNTU14R3lnWldkcTMzWWZmamMKazxKWFTPBK9h4fwH
        2gEnxqDRgxbCwt6Ck5XL9nUGTGU7yncnk9m6apza0E9uvsqTtZuXB1Nq6nFPCL0p
        BlAkRg==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAcnmLrPeTJeKsasfU0qn4sP4lBNeOUgRG4iZDS8nyEo kid@vulkan
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE1Wa1kxQSBKZHhu
        ODRpMkxtblg1b2EyU1NQQkRPdDNvOG44ZFFrc2tRS0tMUTlvL0NBCktoYVRwMmxu
        OFpkdm9ZODNRblJsUUVuSjBHK2ZOQWxUV2E0ZVlQaDIrUDQKLS0tIEdqY1BpTzRX
        amRqU0RSTi9iY1RHZ09LVm9YOTdRUHA3dG90alZFcnIyUncKGuh/5plELiEbRrUW
        pO8yUXxSdxA9otN5fDi5Mj5zZRh7GAHPGtzIRrJEjN446YG4JdorAf+TJ+4Mfibj
        zOpNdg==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHIM3nsk3HxvEcplSqwynh9V2NzlYdI10mrR746SiJZb kid@fw13
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MUZqUjNkendZTjE1NWs0
        dTFvZlVJdTlnRDNlK1EwdDhMZjhlL2l4SEZrCkU4MlNRRnhaTnhXOXZhU0p1MXJh
        bmxGMHArZkVlSmZyS1JPUnVtYngyWFkKLS0tIEczU0hSanNVUlY3TEp5U0c5YTkw
        R3kzaW9jRFZxR3FtL2FLdHRhSmxUUUUKrh51lq0x+hMqLrQztlgHzCL04KUxN7Nn
        npbL2ugvGjGT3aE8FtVwURE9eJ7/tcwrz7fhX5mPfWvAM7FzfFXdrA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1crlwx4k0eaq666fa8dqpq3k9rhkm8qvwf3ewuum8s8hmrzrm55fsl3tk8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-20T14:21:08Z"
  mac: ENC[AES256_GCM,data:4bcFHuSDysWjvxXer75zbUSdv2Y5C6w+dwc8GhdjWIL4Ecr3gYYxN/vZutE0TRsMZWUdDaxyj5yUcoU+6+6nhKWm1WZok1lFlF0Da0CUdmT3xrMCpCvLuGDDrtAG850VkaFx1mtxG+BXmczh3RMN82Dr7gvH9XuK/qg4ihoeVPY=,iv:gCbqpVwYbRVzZhSnyEugmMx8hNJwy8QAWzJ0t+oyTKE=,tag:xlLzdmx7PaJHicHzeJngJw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
