apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsSecret
metadata:
  name: cloudflare-dns-api-token
  namespace: cert-manager
spec:
  secrets:
    - name: cloudflare-dns-api-token
      stringData:
        token: ENC[AES256_GCM,data:mCqCR9YV8y+sZc39aNhvuDhgs05ZOkDFmj2y,iv:ITZwImToSa5LMt4Qt5IashMHh+Cz0ucNMnhAvvWPBKQ=,tag:r/3sF2SkBwBJTropSeVwBg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFE1WkIwUSBJbDNQ
        bC93N2x0ODMxKzExWVlmQzVZblBrYmRHYWZzZGtyaHFHWEp6MGhRClp5UnFxYVFB
        ZW51U24va1ZPUldUUEhTdDdFakpmKzFNNHlYczYyc01SV0UKLS0tIGFFdnpiNWMz
        UkFuQnRLck8zTlgvT3luNVF4aldzVGRtWm1vQkVnSmhXbTQKCXtiX89LodBnQC9q
        TAGHoGm1FHvCdl7Dfvi3Kg04maPHQvy8hZ6NiSPl1a/O+Gdv+uQvn2AV0GHhiJdd
        s+nqXA==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAcnmLrPeTJeKsasfU0qn4sP4lBNeOUgRG4iZDS8nyEo kid@vulkan
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE1Wa1kxQSB2dHNa
        RzFkK1BnYXVBZG95L05aZGVjdmZpZXl2UDlLbmpkUTdjSFBFdlhjCnhOTzYzZDhI
        Z3o5cHNEOGxOWXI1VzRQR25lbjFjZTdPWWNrdXNvZjV2OG8KLS0tIFJ2SGpCM1hw
        WlQ1czQrTE1ZaVFZY3VlVWZ2RHlyT3R1d0kzY2l4MmF6RmcKZmE3EOpcmYwNC2mp
        Z2GxGs5WblpsEvdhtGQfW9P+n1/3B7J7+JJHcWubGhzN4HRv25MW9vvMrr0rTiq8
        xplB9A==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHIM3nsk3HxvEcplSqwynh9V2NzlYdI10mrR746SiJZb kid@fw13
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUlBUdG84Y0NKRFpUUUNE
        TXY4TWkydVR5Q3NZajZqR1BveVlJSEJiaTNnCmluWm0yZWx3dTZkTjZzWDJESnd6
        QmhYZC8wZll3Zy9nQmwrckExc28zR0EKLS0tIEtkVW9ubzdmSERwOHRTcitYRDZ0
        NFIrbFFGc2Y3akNhSXYyMkM1aVdMTWMKrmvXY19x/BtclBBCDTHHaSA+R31ZHkPF
        HyedUQCFi9meQPt/JMwb4ge4wXoHpfrYpWuRVKT8dgTwtayPVqQoOQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1crlwx4k0eaq666fa8dqpq3k9rhkm8qvwf3ewuum8s8hmrzrm55fsl3tk8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-18T15:44:14Z"
  mac: ENC[AES256_GCM,data:eaeVArhtq1SHQFm/HOs4VzFM2793RzHcvEd1b8YZmliunzhtY+mUL7TWCoPzyVXnuTRLdmd1wa+2XJ/aLNR2lswrhehn21IOxKwFJULsXE3frCXNWzbU8CCkgrLRrOxz+h4ndzBMANztyvEmtlTxaUXEELB5UEuAJVTXBqqW6Sc=,iv:UWeq97k2MKdKDDjuXSqm7Pp3pdfZ/DZv7e0sNO7ickU=,tag:FPZm2G7yx7JpEFAwJDkalA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
