---
apiVersion: v1
kind: Service
metadata:
  name: dagger
  annotations:
    external-dns.alpha.kubernetes.io/hostname: dagger.${INTERNAL_DOMAIN}
spec:
  type: LoadBalancer
  selector:
    name: dagger-dagger-helm-engine
  ports:
    - name: dagger
      port: 1234
      targetPort: 1234
      protocol: TCP
