---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/kid/home-ops.git
        revision: HEAD
        files:
          - path: clusters/lab/addons/*/app.yaml
  template:
    metadata:
      name: '{{ .name }}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/kid/home-ops.git
        targetRevision: HEAD
        path: '{{ .path.path | dir }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions: '{{ .syncOptions | toJson }}'
