apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/component: kube-etcd
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    k8s-app: kube-etcd
  name: victoria-metrics-kube-etcd
  namespace: kube-system
subsets:
  - addresses:
      - ip: 10.0.40.10
    ports:
      - name: http-metrics
        port: 2379
        protocol: TCP
