apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/name: victoria-metrics-k8s-stack
  name: vmalertmanager-victoria-metrics
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    receivers:
    - name: blackhole
    route:
      receiver: blackhole
    templates:
    - /etc/vm/templates/**/*.tmpl
