apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: vlsingle
  namespace: monitoring
spec:
  extAuth:
    failOpen: false
    headersToExtAuth:
      - accept
      - cookie
      - location
      - authorization
      - proxy-authorization
      - x-forwarded-proto
    http:
      backendRefs:
        - name: authelia
          namespace: authelia
          port: 80
      headersToBackend:
        - Remote-User
        - Remote-Groups
        - Remote-Name
        - Remote-Email
      path: /api/authz/ext-authz/
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: vlsingle-victoria-metrics-victoria-metrics-k8s-stack
