apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: syncJob
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/name: victoria-metrics-k8s-stack
  name: victoria-metrics-sync-job
  namespace: monitoring
