apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  labels:
    app.kubernetes.io/component: vmalert
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/name: victoria-metrics-k8s-stack
  name: victoria-metrics
  namespace: monitoring
spec:
  configMaps: []
  datasource:
    url: http://vmauth-victoria-metrics-internal.monitoring.svc.cluster.local.:8427
  evaluationInterval: 20s
  externalLabels: {}
  extraArgs:
    http.pathPrefix: /
    remoteWrite.disablePathAppend: "true"
  image:
    tag: v1.152.0
  notifiers:
    - url: http://vmalertmanager-victoria-metrics-0.vmalertmanager-victoria-metrics.monitoring.svc.cluster.local.:9093
  port: "8080"
  remoteRead:
    url: http://vmsingle-victoria-metrics.monitoring.svc.cluster.local.:8428
  remoteWrite:
    url: http://vmsingle-victoria-metrics.monitoring.svc.cluster.local.:8428/api/v1/write
  selectAllByDefault: true
