---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubevirt-upstream
spec:
  interval: 1h
  timeout: 2m
  url: https://github.com/kubevirt/kubevirt
  ref:
    tag: v1.8.1
