apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: grafana-oidc
  namespace: monitoring
spec:
  data:
    - remoteRef:
        key: authelia/secrets/grafana-client-secret
      secretKey: clientSecret
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-oidc
