apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: apps
  namespace: envoy-gateway-system
spec:
  provider:
    kubernetes:
      envoyService:
        name: envoy-gateway-apps
    type: Kubernetes
