apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: apps-tls
  namespace: envoy-gateway-system
spec:
  data:
    - remoteRef:
        key: apps-tls
        property: tls.crt
      secretKey: tls.crt
    - remoteRef:
        key: apps-tls
        property: tls.key
      secretKey: tls.key
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    creationPolicy: Merge
    name: apps-tls
