apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: apps-tls
  namespace: envoy-gateway-system
spec:
  data:
    - match:
        remoteRef:
          property: tls.crt
          remoteKey: apps-tls
        secretKey: tls.crt
    - match:
        remoteRef:
          property: tls.key
          remoteKey: apps-tls
        secretKey: tls.key
  refreshInterval: 1h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: openbao
  selector:
    secret:
      name: apps-tls
