---
# Gateway - HTTP/HTTPS ingress point exposed via BGP
# GatewayClass "cilium" is created by the Cilium Helm chart
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: lab-gateway
  namespace: kube-system
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: lab-gateway-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
