---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage-system

components:
  - ../../components/cluster-values
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./local-path-provisioner/ks.yaml
  - ./nas/ks.yaml
  - ./openebs/ks.yaml
  - ./volsync/ks.yaml
  - ./piraeus-operator/ks.yaml
