apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: miroir
    app.kubernetes.io/name: miroir
  name: miroir-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: miroir-agent
subjects:
  - kind: ServiceAccount
    name: miroir-agent
    namespace: miroir-system
