apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: miroir.home-operations.com
spec:
  attachRequired: false
  fsGroupPolicy: ReadWriteOnceWithFSType
  podInfoOnMount: false
  storageCapacity: false
  volumeLifecycleModes:
    - Persistent
