apiVersion: miroir.home-operations.com/v1alpha1
kind: MiroirNode
metadata:
  name: k3s-prd-0
spec:
  pools:
    - lvmthin:
        device: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_incus_miroir--data
      name: default
