---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../kubernetes/apps/external-secrets/
  - ../../../kubernetes/apps/flux-system/
  - ../../../kubernetes/apps/kube-system/
  - ../../../kubernetes/apps/network-system/
  - ../../../kubernetes/apps/observability/
  - ../../../kubernetes/apps/virtualization-system/
  # - ./storage-system/

patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: kubevirt
      namespace: virtualization-system
    patch: |-
      - op: replace
        path: /spec/path
        value: ./clusters/metal/apps/virtualization-system/kubevirt
