---
# yaml-language-server: $schema=https://k8s-versioned-schemas.pages.dev/keda/2.19.0/scaledobject_v1alpha1.json
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ${APP}
spec:
  advanced:
    restoreToOriginalReplicaCount: true
  pollingInterval: 10
  cooldownPeriod: 0
  idleReplicaCount: 0
  minReplicaCount: ${REPLICAS:=1}
  maxReplicaCount: ${REPLICAS:=1}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${APP}
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://vmsingle-victoria-metrics.observability.svc:8428/prometheus
        query: max(kube_deployment_status_replicas_available{namespace="${NFS_NAMESPACE:=storage-system}",deployment="${NFS_DEPLOYMENT:=nfs}"}) OR on() vector(0)
        threshold: "1"
