---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
spec:
  dependsOn:
    - name: grafana-operator
    - name: external-secrets
      namespace: external-secrets
    - name: volsync
      namespace: storage-system
  interval: 1h
  path: ./kubernetes/apps/observability/grafana
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: observability
  wait: true
  components:
    - ../../../components/volsync/
  postBuild:
    substitute:
      APP: grafana
      VOLSYNC_PUID: "10001"
      VOLSYNC_PGID: "10001"
