apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: authelia-secrets
  namespace: authelia
spec:
  data:
    - remoteRef:
        key: authelia/secrets/reset-password-jwt-secret
      secretKey: identity_validation.reset_password.jwt.hmac.key
    - remoteRef:
        key: authelia/secrets/session-encryption-key
      secretKey: session.encryption.key
    - remoteRef:
        key: authelia/secrets/storage-encryption-key
      secretKey: storage.encryption.key
    - remoteRef:
        key: authelia/secrets/oidc-hmac-secret
      secretKey: identity_providers.oidc.hmac.key
    - remoteRef:
        key: authelia/secrets/smtp-password
      secretKey: notifier.smtp.password.txt
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authelia-secrets
