apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: authelia-extra
  namespace: authelia
spec:
  data:
    - remoteRef:
        decodingStrategy: Base64
        key: authelia/secrets/oidc-jwks-key
      secretKey: jwksKey
    - remoteRef:
        key: authelia/secrets/argocd-client-secret
      secretKey: argocdClientSecret
    - remoteRef:
        decodingStrategy: Base64
        key: authelia/secrets/users-database
      secretKey: usersDatabase
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authelia-extra
    template:
      data:
        oidc.client.argocd.secret: '{{ printf "$plaintext$%s" .argocdClientSecret }}'
        oidc.jwks.rsa.key: '{{ .jwksKey }}'
        users_database.yml: '{{ .usersDatabase }}'
