apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia
  namespace: authelia
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    apiGroup: kopiur.home-operations.com
    kind: Restore
    name: authelia
  resources:
    requests:
      storage: 1Gi
  storageClassName: miroir
