apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/name: authelia
  name: authelia
  namespace: authelia
spec:
  endpoints:
    - path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - authelia
  selector:
    matchLabels:
      app.kubernetes.io/instance: authelia
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: authelia
      app.kubernetes.io/version: 4.39.24
      helm.sh/chart: authelia-0.11.22
