apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: authelia
  namespace: authelia
spec:
  policyRef:
    name: authelia
  schedule:
    cron: H * * * *
    jitter: 5m
    runOnCreate: false
