---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: virtualization

components:
  - ../../components/cluster-values
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./kubevirt/source.yaml
  - ./kubevirt/ks.yaml
  - ./kubevirt/ks.config.yaml
  - ./cdi/ks.yaml
