apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso-cluster
          serviceAccountRef:
            name: external-secrets
      path: secret
      server: https://openbao.kidibox.net:8200
      version: v2
