apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao
spec:
  provider:
    openBao:
      auth:
        appRole:
          path: approle
          roleId: external-secrets
          secretRef:
            key: secret_id
            name: openbao-approle
            namespace: external-secrets
      path: secret
      server: http://openbao.kidibox.net:8200
      version: v2
