apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/metrics: webhook
    app.kubernetes.io/name: external-secrets-webhook
  name: external-secrets-webhook-metrics
  namespace: external-secrets
spec:
  endpoints:
    - honorLabels: false
      interval: 30s
      port: metrics
      scrapeTimeout: 25s
  namespaceSelector:
    matchNames:
      - external-secrets
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets
      app.kubernetes.io/metrics: webhook
      app.kubernetes.io/name: external-secrets-webhook
