---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate-reolink-doorbell
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ${ONEPASSWORD_STORE}
  target:
    name: frigate-reolink-doorbell-secret
    template:
      data:
        FRIGATE_REOLINK_USERNAME: "{{ .username }}"
        FRIGATE_REOLINK_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: reolink-doorbell
