---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate-reolink-litters
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ${ONEPASSWORD_STORE}
  target:
    name: frigate-reolink-litters-secret
    template:
      data:
        FRIGATE_REOLINK_LITTERS_USERNAME: "{{ .username }}"
        FRIGATE_REOLINK_LITTERS_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: reolink-litters
