apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: mikrotik-credentials
  namespace: external-dns
spec:
  data:
    - remoteRef:
        key: mikrotik-credentials/credentials/password
      secretKey: MIKROTIK_PASSWORD
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mikrotik-credentials
