apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsSecret
metadata:
  name: mikrotik-credentials
  namespace: external-dns
spec:
  secrets:
    - name: mikrotik-credentials
      stringData:
        MIKROTIK_PASSWORD: ENC[AES256_GCM,data:69yRIPA+ehEz57MYxP0rzNbAMlk=,iv:4a6aQrPZLK/OgkiVvjOedPrXgloeQ2n178D1XxWOIuE=,tag:Y16VyE0d/+0lE+ai5wpIBw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFE1WkIwUSBGaHRq
        Vzk4ZStwL1pGMS9IMDllbG1YbjNCS2JDblhkdEsyR1dwRUtuTFN3CndZSmFGL3Uz
        VnhQQTd3bTdNQnF0ZTJVNi9MdDR4VzhsaEJObnljTnBoMEUKLS0tIEx0VFpGOHQ4
        UFQzY1JuN0wreHV3VGhmZGJyTU1ScG5JcWYybzZHZUdwSVkKdGdIMHr4O73gNPWD
        K+tMrE58nzbm4PGI0vrSLFcva6m6Qq/x/7scY1Aa2wRDtrJ1yc86JOcvE8vH/f5t
        EOQvEg==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAcnmLrPeTJeKsasfU0qn4sP4lBNeOUgRG4iZDS8nyEo kid@vulkan
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE1Wa1kxQSBMSTlM
        SnlMaWx3cUFLeUJPOUkyS1BHNTdPak80Q1A4ekM4a2tWNDRXMzIwCjZmUVBJYXMx
        OHlxVzdxMFp6QVBRWTlLRXd5azlNTTEwdkF1ZkpoTkQ0N0kKLS0tIG5JZFhxVmk1
        SXlXZkJxZG1XeXFYTHVOM2tNMXI3YitBTjlwNkJib0E3K2cKU1QCsQB+u0p/0mR8
        JHxa02qAKAHo8CJQQoNH7qfTq7TfbJflEj19/YAL2yOmEbBD4jAZLcIfwE5qV0yL
        lwVpMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHIM3nsk3HxvEcplSqwynh9V2NzlYdI10mrR746SiJZb kid@fw13
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJM1FrQ2xlMGJMY0Fmc0xV
        NFBlMDdzRGd0Qi85aVNkV2lzL05DNHQreENFClRQd3hIbWkyV1QyMVZkQ3NpNGFS
        VXJQVXgzRUt4cGQ0OFVBWCtsNFVndGsKLS0tIHM4SCt5MGtuNmFVVFN5ejVDckZu
        dmhlZkZwNW15U2tmN2gwL1R6WWpnUG8KUsPscYELdavXZkIwXroXBcNyv8aJ9unm
        hXTUBXjMQBnT1Ox+g7fGIsr063MaiMRfEy+JmWtBTaBOnXsP0NxKbw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1crlwx4k0eaq666fa8dqpq3k9rhkm8qvwf3ewuum8s8hmrzrm55fsl3tk8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-17T18:41:10Z"
  mac: ENC[AES256_GCM,data:E2uqt5UJ3BEIGuIV2fctSf7yS3Mz9/zXYkMMOXCzynAM+aiQlKDGdwDQ9Q2+y5UbG43ttAAtyMSbvGpQMKNcFLc/hL3RTbbyWQtG+GLP6J1aBcoJ9xgWKZ+mbWmuPEliic5//eqRUK36+9KXPk8I+Oe/G2LZ80Q/zE2Rn3FvPP4=,iv:Inm66jdZU0oTMmlaVcqwxO8i6Igo9eLmjYzhrbr7iOg=,tag:ak//F6zaA9yFnk0/INo9/A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
