apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsSecret
metadata:
  name: mikrotik-credentials
  namespace: external-dns
spec:
  secrets:
    - name: mikrotik-credentials
      stringData:
        MIKROTIK_PASSWORD: ENC[AES256_GCM,data:hvRVy2Bl4KlB3Ie4MwI6l4vzxuI=,iv:C2iuzMbKJjefFkTz4FsZgtUp5Lw9yk1RybBN2o+NI4k=,tag:1TdC1PuO4zQCOOJZ9ybaYQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFE1WkIwUSB6Q2FE
        eHJsdXlLWHArcDMzVVQ4TU53T2d2ZzRXL0tqVnlxTzNBRDA4dml3CkgxZzNwR2E1
        NFYvSW8wVTJoT1d0eXRidTdMem5DOWZOOG5SVml3SUR1NnMKLS0tIDJDZ0JsQW5p
        OFJQT0lJa0FFZCtaNHdMSllTckUwWndaUDZ0OFpaaWxZa3MKXPIakAQ5WvWbWfSh
        viVfdq7e6p+N1OlfsyZnkF68f/xkaEk3s0pYcp/yk+MknzelksXoSbKGLYFD5nDG
        gSHRZQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAcnmLrPeTJeKsasfU0qn4sP4lBNeOUgRG4iZDS8nyEo kid@vulkan
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE1Wa1kxQSBHd0Zh
        T3FBRm9sb2phYmRBUm02Vk1jamFuUU4yMnZyTUI4WktmZ1pFZUg0ClVXVXJiNmQy
        dU1Qa0I5WHJaUmZYdC9URUZ6WEJEV1hzeThLcTlMc2VKMTgKLS0tIEhGa2lhSTNB
        ZVVwa04zUmlzcEl1NEVQMWNBcUw3VGt1dXR5dzU1cGxKWjAKDYzNrDuUYlxI6Pg3
        jnxTG9nLTKBihlXnct9nPui38zrn3mENUFFmuD/6Xk3kHzXIvJCN3sz6QdzYAlwl
        N5fC3w==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHIM3nsk3HxvEcplSqwynh9V2NzlYdI10mrR746SiJZb kid@fw13
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTFo1eDRxVml0VVBvbWFl
        ZGFvOUthSXFWcVl1L3RUUURxQ1pOaWwzc2pZCnJneUgvUTQ3WVpUMm5zMkR5ZGp6
        Mlp2dmlkSVZvYmFsVEdRVEZMR3lKencKLS0tIERmcG8ycjZGSEtVZWcwamNVSUVs
        Ynh3aGhDQnlJdlpQb0ovWVQ3TWhNck0KG6TV4kD+RTLXAvpnLJORSG3R/LfHWs3n
        lwHV6jet7iSWsADxK5HPtM0V0YqlY61BwUCOn18nPxT60pUv0ozltQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1crlwx4k0eaq666fa8dqpq3k9rhkm8qvwf3ewuum8s8hmrzrm55fsl3tk8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-20T15:29:51Z"
  mac: ENC[AES256_GCM,data:v/5dtZUrij0XywZOmIFMY9d2qXvnnuMyCwvpPd+L4DCkQh5oZ1BvdxNnQNw73fDiO+AURKj+BxRPOelJ3Bpv7QX3mRRVRsamuL2YW1tbnUIZxfB3yBs0D/FE47a1ceohRjAzgXysPLzdLEBYyX943s6vjVEkAmhMM01k+qmNZ1A=,iv:HHAsARFYdWqSAuLuqbQE8ZE1n7FvqH0eoMl3VLSGEA8=,tag:KliV5rAi16xP+dLX2eDQ+w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
