apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsSecret
metadata:
  name: mikrotik-credentials
  namespace: external-dns
spec:
  secrets:
    - name: mikrotik-credentials
      stringData:
        MIKROTIK_PASSWORD: ENC[AES256_GCM,data:V1MFfRoQ1ClzYZ+++JiMB06XhJw=,iv:E/gAfsdiy+INd2GylunKvH7Q67egWsCF1dEpCOi0kBw=,tag:D7ru97CEJr5SpwCKLxVd2A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFE1WkIwUSA5N0lB
        dVhQZWovdUVzYzlsVEdGM3dGZ1ZwQ2lWNHBZcW04Nmo5VTRFeDFVClBFUXB6bDhG
        RG5TbEpmYllvZkJHY3BEOUpyNTF3b3Fmc1c2NTRRMkNxMGcKLS0tIG1ZMGZDdjcz
        ZEVraHVBZERMc3dOcitkMUNDVGhvcTM4dlNHK3FHOEVWQk0KDbG3gYbUP8oSxBM8
        ftwR3wCN/xjk5+RPDWxfKpiBvl+2B6r7e3dsBQP6i4FLisxu/m2CkrNBP3dWo4np
        dI0/5Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAcnmLrPeTJeKsasfU0qn4sP4lBNeOUgRG4iZDS8nyEo kid@vulkan
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE1Wa1kxQSBxT3J1
        ckw5OGlwVzZyYVNBaDhVQlBhemlvcDNOM1hibEtRUmhXNDF5b1RJCk9rMHVqYnZU
        UVp5R1RENzhNdElSWG1tVEFQVGRhd2REVkdBNlA4TnRrZjAKLS0tIHJBTFk1c1dQ
        enRGVEZRdkZpYTNmYW8zS0MyWExSS2FsUVhhSlAzMEI5N1EKALqGy1AhMWF0Beel
        4KPAIN3pu8hVa3awHHE9wy53M5Vw6VOIUIRLidvbTfnjo1xJGc3yZ379S+QQv4NF
        8lni5g==
        -----END AGE ENCRYPTED FILE-----
      recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHIM3nsk3HxvEcplSqwynh9V2NzlYdI10mrR746SiJZb kid@fw13
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TmZGa1dFR010Zk1uME1V
        QWdrWHd2RHlOcVNsSmQ3L2hIcVppVTVtSzNJCjl0WktyaXA2emxmU3RIUzEzL1Yx
        QUVaM3FvSHNBNnEyRGxBM2VGTHB5b1EKLS0tIDhaeEJVQ2xucFJMZ2hmdm9NZzNS
        NEFISHFhWFh1V2plQmJCUlF6YmZGRVkKxNgqk2IZeX81opIcdBTKiDPOTkSOXSVT
        tspG0kTvz1hXRX8ziS2Ha6VKIofGzIcH7w5K+/8d8P7uHrUE+OQdow==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1crlwx4k0eaq666fa8dqpq3k9rhkm8qvwf3ewuum8s8hmrzrm55fsl3tk8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-31T19:32:10Z"
  mac: ENC[AES256_GCM,data:0vaIe8XaW97HW0TRfxcq69cpHAESM+2e4DiB+zdTAlS+8O2u567fN2lVvrwNjVpW/Mmy9Z/j98oKPsrhcgY2tSis/cHHHsGXpl6j9/dlAl0b0JIEBZ9C6u7ZIlIUBSXAW0ZygtS7SecOtDr+49xn9lHhaaHidasVsZNFdQXyWNk=,iv:ecJ40E6EVN3fPT9jKZ9JqcorgPLdQtPp2OJ0LAPx1wc=,tag:OSv/RqYFOLkEXxILtnd3hw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
