name: Dagger Checks

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Dagger checks
        uses: dagger/checks@v1.0.0
